# Generated by Django 3.2.6 on 2021-11-12 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(choices=[('gujarat', 'Gujarat'), ('rajasthan', 'Rajasthan'), ('maharashtra', 'Maharashtra')], max_length=100)),
                ('city', models.CharField(choices=[('vadodara', 'Vadodara'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar'), ('mumbai', 'Mumbai'), ('jaipur', 'Jaipur'), ('surat', 'Surat'), ('jodhpur', 'Jodhpur')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to='profile_photos')),
                ('resume', models.FileField(upload_to='resume/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
