# Generated by Django 3.2.6 on 2021-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20211112_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('vadodara', 'Vadodara'), ('gandhinagar', 'Gandhinagar'), ('ahmedabad', 'Ahmedabad'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('surat', 'Surat'), ('udaipur', 'Udaipur'), ('nagpur', 'Nagpur'), ('jodhpur', 'Jodhpur'), ('jaipur', 'Jaipur')], max_length=100),
        ),
    ]
