# Generated by Django 3.2.6 on 2021-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20211112_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar'), ('vadodara', 'Vadodara'), ('jodhpur', 'Jodhpur'), ('nagpur', 'Nagpur'), ('ahmedabad', 'Ahmedabad'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('surat', 'Surat'), ('jaipur', 'Jaipur')], max_length=100),
        ),
    ]
