# Generated by Django 3.2.6 on 2021-11-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20211112_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('nagpur', 'Nagpur'), ('pune', 'Pune'), ('surat', 'Surat'), ('jaipur', 'Jaipur'), ('vadodara', 'Vadodara'), ('gandhinagar', 'Gandhinagar'), ('udaipur', 'Udaipur'), ('jodhpur', 'Jodhpur'), ('mumbai', 'Mumbai'), ('ahmedabad', 'Ahmedabad')], max_length=100),
        ),
    ]
