# Generated by Django 3.2.6 on 2021-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('ahmedabad', 'Ahmedabad'), ('pune', 'Pune'), ('jaipur', 'Jaipur'), ('gandhinagar', 'Gandhinagar'), ('surat', 'Surat'), ('udaipur', 'Udaipur'), ('nagpur', 'Nagpur'), ('vadodara', 'Vadodara'), ('jodhpur', 'Jodhpur'), ('mumbai', 'Mumbai')], max_length=100),
        ),
    ]
