# Generated by Django 3.2.6 on 2021-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('vadodara', 'Vadodara'), ('gandhinagar', 'Gandhinagar'), ('ahmedabad', 'Ahmedabad'), ('jodhpur', 'Jodhpur'), ('mumbai', 'Mumbai'), ('surat', 'Surat'), ('udaipur', 'Udaipur'), ('pune', 'Pune'), ('nagpur', 'Nagpur'), ('jaipur', 'Jaipur')], max_length=100),
        ),
    ]
