# Generated by Django 3.2.7 on 2021-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
