# Generated by Django 3.2.6 on 2021-11-10 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('gujarat', 'Gujarat'), ('rajasthan', 'Rajasthan'), ('maharashtra', 'Maharashtra')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('city', models.CharField(choices=[('pune', 'Pune'), ('jodhpur', 'Jodhpur'), ('mumbai', 'Mumbai'), ('vadodara', 'Vadodara'), ('ahmedabad', 'Ahmedabad'), ('gandhinagar', 'Gandhinagar'), ('jaipur', 'Jaipur'), ('surat', 'Surat'), ('udaipur', 'Udaipur'), ('nagpur', 'Nagpur')], max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
