# Generated by Django 3.2.6 on 2021-11-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20211110_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('ahmedabad', 'Ahmedabad'), ('vadodara', 'Vadodara'), ('pune', 'Pune'), ('nagpur', 'Nagpur'), ('surat', 'Surat'), ('mumbai', 'Mumbai'), ('jodhpur', 'Jodhpur'), ('jaipur', 'Jaipur'), ('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
