# Generated by Django 3.2.6 on 2021-11-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0003_auto_20211110_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('pune', 'Pune'), ('nagpur', 'Nagpur'), ('jaipur', 'Jaipur'), ('surat', 'Surat'), ('udaipur', 'Udaipur'), ('vadodara', 'Vadodara'), ('mumbai', 'Mumbai'), ('jodhpur', 'Jodhpur'), ('gandhinagar', 'Gandhinagar'), ('ahmedabad', 'Ahmedabad')], max_length=50),
        ),
    ]
