# Generated by Django 3.2.6 on 2021-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20211111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('vadodara', 'Vadodara'), ('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar'), ('mumbai', 'Mumbai'), ('surat', 'Surat'), ('nagpur', 'Nagpur'), ('ahmedabad', 'Ahmedabad'), ('jaipur', 'Jaipur'), ('jodhpur', 'Jodhpur'), ('pune', 'Pune')], max_length=50),
        ),
    ]
