# Generated by Django 3.2.6 on 2021-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar'), ('surat', 'Surat'), ('vadodara', 'Vadodara'), ('pune', 'Pune'), ('jodhpur', 'Jodhpur'), ('mumbai', 'Mumbai'), ('ahmedabad', 'Ahmedabad'), ('jaipur', 'Jaipur'), ('nagpur', 'Nagpur')], max_length=50),
        ),
    ]
