# Generated by Django 3.2.6 on 2021-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('mumbai', 'Mumbai'), ('pune', 'Pune'), ('udaipur', 'Udaipur'), ('gandhinagar', 'Gandhinagar'), ('ahmedabad', 'Ahmedabad'), ('nagpur', 'Nagpur'), ('jaipur', 'Jaipur'), ('vadodara', 'Vadodara'), ('surat', 'Surat'), ('jodhpur', 'Jodhpur')], max_length=50),
        ),
    ]
