# Generated by Django 3.2.6 on 2021-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('udaipur', 'Udaipur'), ('vadodara', 'Vadodara'), ('jaipur', 'Jaipur'), ('ahmedabad', 'Ahmedabad'), ('jodhpur', 'Jodhpur'), ('nagpur', 'Nagpur'), ('pune', 'Pune'), ('mumbai', 'Mumbai'), ('surat', 'Surat'), ('gandhinagar', 'Gandhinagar')], max_length=100),
        ),
    ]
